In [1]:
import numpy as np

In [7]:
## Regular Multiplication
c = np.array([[1,2,3],[1,4,6]])
d = np.array([[0,0],[1,2],[1,2]])
np.matmul(c,d)

array([[ 5, 10],
       [10, 20]])

In [5]:
c = np.array([[0,0],[0,1],[1,0],[1,1]])
d = np.array([[1,1],[1,1]])
np.matmul(c,d)

array([[0, 0],
       [1, 1],
       [1, 1],
       [2, 2]])

In [10]:
c = np.array([[0,0],[1,1],[1,1],[2,2]])
d = np.array([[0,-1]])
c+d

array([[ 0, -1],
       [ 1,  0],
       [ 1,  0],
       [ 2,  1]])

In [16]:
def relu(X):
   return np.maximum(0,X)

r = relu(c+d)

In [17]:
e = np.array([1,-2])
np.matmul(r, e)

array([0, 1, 1, 0])